### ISSUE TITLE
Stamps with short hostnames are marked invalid

### ISSUE THREAD

**Issue by ymn** [jedisct1/go-dnsstamps#4]
We currently have issues with using dnscrypt-proxy clients with our DoH-Servers because our short hostnames are marked invalid.

Following stamps:

IP Address: 
Host name: ns3.com
Hashes: 
Path: /

Stamp: sdns://AgAAAAAAAAAAAAAHbnMzLmNvbQEv

Results in following error: [FATAL] Stamp error for the static [ns3-server] definition: [Stamp is too short]

but 

IP Address: 
Host name: ns3dnsresolver.com
Hashes: 
Path: /

Stamp: sdns://AgAAAAAAAAAAAAASbnMzZG5zcmVzb2x2ZXIuY29tCC9jL3VzeTV2
Result: works without problems

What do we expect:

That short hostnames are also marked valid.

Because dnscrypt-proxy is using this repo to fetch and validate dns stamps, resolvers with short hostnames are not working on dnscrypt-proxy because it stucks on "stamp too short" error.

**Comment by jedisct1** [comment]
Good catch, the limit was a too high.

Should be good now. Thanks!
